// <auto-generated />
using BusinessLogic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApplication.Migrations
{
    [DbContext(typeof(VacanciesContext))]
    partial class VacanciesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessLogic.Models.Vacancie", b =>
                {
                    b.Property<string>("Identificator")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Contacts");

                    b.Property<string>("Description");

                    b.Property<string>("EmployementType");

                    b.Property<string>("Headline");

                    b.Property<string>("Organization");

                    b.Property<string>("Salary");

                    b.Property<string>("Url");

                    b.HasKey("Identificator");

                    b.ToTable("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
